apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduler-plugins.schedulerName" . }}
  namespace:
    {{ include "scheduler-plugins.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduler-plugins.controllerName" . }}
  namespace:
    {{ include "scheduler-plugins.namespace" . }}
